security:
    encoders:
        App\Entity\Usuarios:
            algorithm: bcrypt

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Usuarios
                property: usuario

    firewalls:
        main:
            anonymous: true
            form_login:
                login_path: login
                check_path: login
                default_target_path: app_avisos_index
            logout:
                path: logout
                target: login

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
