vich_uploader:
    db_driver: orm

    mappings:
        avisos_images:
            uri_prefix: /images/avisos
            upload_destination: '%kernel.project_dir%/public/images/avisos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
